export function getAdminLoginHTML(): string {
  return `<!DOCTYPE html><html><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'><title>Admin Login</title><link href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css' rel=stylesheet><link rel=stylesheet href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css'><style>body{min-height:100vh;display:flex;align-items:center;background:linear-gradient(135deg,#1a1a2e,#16213e,#0f3460)}.card{border:none;border-radius:12px;box-shadow:0 8px 32px rgba(0,0,0,.3)}</style></head><body><div class=container><div class='row justify-content-center'><div class=col-md-4><div class=card><div class='card-body p-4'><h4 class='text-center mb-4'><i class='bi bi-shield-lock'></i> Admin Login</h4><div id=error class='alert alert-danger d-none'></div><form id=f><div class=mb-3><label class=form-label>Username</label><input type=text class=form-control name=username required autofocus></div><div class=mb-3><label class=form-label>Password</label><input type=password class=form-control name=password required></div><button type=submit class='btn btn-primary w-100'>Sign In</button></form></div></div></div></div></div><script>document.getElementById('f').onsubmit=async(e)=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const r=await fetch('/admin/login',{method:'POST',body:new FormData(e.target)});const d=await r.json();if(d.ok)location.reload();else{document.getElementById('error').textContent=d.error;document.getElementById('error').classList.remove('d-none')}}finally{b.disabled=false}}</script></body></html>`;
}

export function getAdminDashboardHTML(origin: string): string {
  const redirectUri = origin + '/google_callback';
  return `<!DOCTYPE html><html><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'><title>Admin Panel</title>
<link href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css' rel=stylesheet>
<link rel=stylesheet href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css'>
<style>
:root{--sw:240px;--sc:60px;--sb:#1a1d21}*{box-sizing:border-box}body{background:#f0f2f5;margin:0;font-family:system-ui}
.sb{background:var(--sb);min-height:100vh;width:var(--sw);position:fixed;top:0;left:0;z-index:100;transition:width .25s;overflow:hidden;display:flex;flex-direction:column}
.sb.collapsed{width:var(--sc)}
.sb .brand{padding:16px;display:flex;align-items:center;gap:10px;color:#fff;border-bottom:1px solid rgba(255,255,255,.1)}
.sb .brand h5{margin:0;white-space:nowrap}
.sb.collapsed .brand h5,.sb.collapsed .brand small,.sb.collapsed .nav-text,.sb.collapsed .sb-footer .btn span{display:none}
.sb .nav-link{color:#9ca3af;padding:10px 16px;border-radius:8px;margin:2px 8px;display:flex;align-items:center;gap:10px;text-decoration:none;white-space:nowrap;transition:.15s}
.sb .nav-link:hover,.sb .nav-link.active{color:#fff;background:rgba(255,255,255,.08)}
.sb .nav-link i{font-size:18px;width:24px;text-align:center}
.sb-footer{padding:12px 8px;margin-top:auto;border-top:1px solid rgba(255,255,255,.1)}
.sb-footer .btn{width:100%;margin-bottom:6px;display:flex;align-items:center;gap:8px;justify-content:center}
.main{margin-left:var(--sw);padding:24px;min-height:100vh;transition:margin-left .25s}
.main.expanded{margin-left:var(--sc)}
.card{border:none;border-radius:12px;box-shadow:0 1px 8px rgba(0,0,0,.06)}
.sc{transition:transform .15s}.sc:hover{transform:translateY(-2px)}
.table th{font-weight:600;font-size:.8rem;text-transform:uppercase;color:#6c757d}
#tc{position:fixed;top:16px;right:16px;z-index:9999}
@media(max-width:768px){.sb{width:var(--sc)}.sb .nav-text,.sb .brand h5,.sb .brand small,.sb-footer .btn span{display:none}.main{margin-left:var(--sc)}}
</style></head><body>
<div id=tc></div>
<div class=sb id=sidebar><div class=brand><i class="bi bi-gear-fill" style="font-size:24px;cursor:pointer" onclick="toggleSidebar()"></i><div><h5>Admin</h5><small style="color:#94a3b8">Drive Index</small></div></div>
<nav class="nav flex-column mt-2">
<a class="nav-link active" href=# data-tab=dashboard><i class="bi bi-speedometer2"></i><span class=nav-text>Dashboard</span></a>
<a class="nav-link" href=# data-tab=credentials><i class="bi bi-person-badge"></i><span class=nav-text>Credentials</span></a>
<a class="nav-link" href=# data-tab=drives><i class="bi bi-hdd-stack"></i><span class=nav-text>Drives</span></a>
<a class="nav-link" href=# data-tab=config><i class="bi bi-sliders"></i><span class=nav-text>Configuration</span></a>
<a class="nav-link" href=# data-tab=sa><i class="bi bi-key"></i><span class=nav-text>Service Accounts</span></a>
<a class="nav-link" href=# data-tab=google-login><i class="bi bi-google"></i><span class=nav-text>Google Login</span></a>
<a class="nav-link" href=# data-tab=security><i class="bi bi-shield-check"></i><span class=nav-text>Security</span></a>
</nav>
<div class=sb-footer><a href=/ class="btn btn-outline-light btn-sm" target=_blank><i class="bi bi-box-arrow-up-right"></i><span>View Site</span></a>
<a href=/admin/logout class="btn btn-outline-danger btn-sm"><i class="bi bi-box-arrow-left"></i><span>Logout</span></a></div></div>
<div class=main id=main><div class="text-center py-5"><div class="spinner-border text-primary" style="width:3rem;height:3rem" role="status"></div><p class="text-muted mt-3">Loading dashboard...</p></div></div>
<div class="modal fade" id=credM tabindex=-1><div class=modal-dialog><div class=modal-content><div class=modal-header><h5 class=modal-title>Add OAuth Credential</h5><button type=button class=btn-close data-bs-dismiss=modal></button></div><div class=modal-body><div class=mb-3><label class=form-label>Name</label><input type=text class=form-control id=cred-name></div><div class=mb-3><label class=form-label>Client ID</label><input type=text class=form-control id=cred-cid></div><div class=mb-3><label class=form-label>Client Secret</label><input type=password class=form-control id=cred-cs></div><div class=mb-3><label class=form-label>Refresh Token</label><input type=password class=form-control id=cred-rt></div></div><div class=modal-footer><button class="btn btn-secondary" data-bs-dismiss=modal>Cancel</button><button class="btn btn-primary" onclick=addOAuthCred()>Save</button></div></div></div></div>
<div class="modal fade" id=dm tabindex=-1><div class=modal-dialog><div class=modal-content><div class=modal-header><h5 class=modal-title id=dmt>Add Drive</h5><button type=button class=btn-close data-bs-dismiss=modal></button></div><div class=modal-body><input type=hidden id=dei><div class=mb-3><label class=form-label>Name</label><input type=text class=form-control id=dn></div><div class=mb-3><label class=form-label>Drive/Folder ID</label><input type=text class="form-control font-monospace" id=di placeholder="0ABCD or root"><button class="btn btn-outline-info btn-sm mt-1" onclick=fetchRoot()><i class="bi bi-arrow-repeat"></i> Fetch Info</button> <button class="btn btn-outline-success btn-sm mt-1" onclick=browseShared()><i class="bi bi-list-ul"></i> Browse Drives</button><small id=fetchResult class="d-block mt-1 text-muted"></small></div><div class=mb-3><label class=form-label>Auth Type</label><select class=form-select id=d-auth onchange=onAuthTypeChange()><option value=oauth>OAuth Credential</option><option value=service_account>Service Account</option></select></div><div id=d-auth-oauth class=mb-3><label class=form-label>Credential</label><select class=form-select id=d-cred><option value="">--Select--</option></select></div><div id=d-auth-sa class=mb-3 style="display:none"><label class=form-label>Service Account</label><select class=form-select id=d-sa><option value="">--Select--</option></select></div><div class="form-check mb-3"><input class=form-check-input type=checkbox id=dp><label class=form-check-label for=dp>Protect links</label></div></div><div class=modal-footer><button class="btn btn-secondary" data-bs-dismiss=modal>Cancel</button><button class="btn btn-primary" onclick=saveDrive()>Save</button></div></div></div></div>
<div class="modal fade" id=cm tabindex=-1><div class=modal-dialog><div class=modal-content><div class=modal-header><h5 class=modal-title>Add Config</h5><button type=button class=btn-close data-bs-dismiss=modal></button></div><div class=modal-body><div class=mb-3><label class=form-label>Key</label><input type=text class="form-control font-monospace" id=ck></div><div class=mb-3><label class=form-label>Value</label><input type=text class=form-control id=cv></div></div><div class=modal-footer><button class="btn btn-secondary" data-bs-dismiss=modal>Cancel</button><button class="btn btn-primary" onclick=addCfgKey()>Add</button></div></div></div></div>
<div class="modal fade" id=sm tabindex=-1><div class="modal-dialog modal-lg"><div class=modal-content><div class=modal-header><h5 class=modal-title>Add Service Account</h5><button type=button class=btn-close data-bs-dismiss=modal></button></div><div class=modal-body><textarea class="form-control font-monospace" id=sj rows=10 placeholder="Paste JSON..."></textarea></div><div class=modal-footer><button class="btn btn-secondary" data-bs-dismiss=modal>Cancel</button><button class="btn btn-primary" onclick=addSA()>Add</button></div></div></div></div>
<div class="modal fade" id=bulkM tabindex=-1><div class=modal-dialog><div class=modal-content><div class=modal-header><h5 class=modal-title>Add All Drives from Credential</h5><button type=button class=btn-close data-bs-dismiss=modal></button></div><div class=modal-body><p class="text-muted small">Fetches My Drive + all shared drives accessible by the selected credential and adds them in bulk. Duplicates are skipped.</p><div class=mb-3><label class=form-label>Auth Type</label><select class=form-select id=bulk-auth onchange=onBulkAuthChange()><option value=oauth>OAuth Credential</option><option value=service_account>Service Account</option></select></div><div id=bulk-oauth-sel class=mb-3><label class=form-label>OAuth Credential</label><select class=form-select id=bulk-cred><option value="">--Select--</option></select></div><div id=bulk-sa-sel class=mb-3 style="display:none"><label class=form-label>Service Account</label><select class=form-select id=bulk-sa><option value="">--Select--</option></select></div><div id=bulk-result></div></div><div class=modal-footer><button class="btn btn-secondary" data-bs-dismiss=modal>Cancel</button><button class="btn btn-success" id=bulk-btn onclick=bulkAddDrives()><i class="bi bi-plus-circle"></i> Add All Drives</button></div></div></div></div>
<script src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js'></script>
<script>
const REDIRECT_URI='${redirectUri}';
let AD=[],AC=[],ASA=[],ACREDS=[];
const $=s=>document.getElementById(s);
const esc=s=>s==null?'':String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function toggleSidebar(){const sb=$('sidebar'),mn=$('main');sb.classList.toggle('collapsed');mn.classList.toggle('expanded');localStorage.setItem('sb_collapsed',sb.classList.contains('collapsed'))}
if(localStorage.getItem('sb_collapsed')==='true'){$('sidebar').classList.add('collapsed');$('main').classList.add('expanded')}
function toast(m,t='success'){const id='t'+Date.now();$('tc').insertAdjacentHTML('beforeend','<div id="'+id+'" class="toast show align-items-center text-bg-'+t+' border-0 mb-2"><div class="d-flex"><div class="toast-body">'+m+'</div><button class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"></button></div></div>');setTimeout(()=>{const e=$(id);if(e)e.remove()},3000)}
async function api(p,b){const o=b?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}:{};const r=await fetch('/admin/api/'+p,o);const d=await r.json();if(d.error)throw new Error(d.error);return d}
const BK=['auth.enable_login','auth.enable_signup','ui.logo_image','ui.fixed_header','ui.hide_footer','ui.credit','ui.display_size','ui.display_download','ui.render_readme_md','ui.show_logout_button'];
const SK={'site.download_mode':['path','id'],'player.player':['videojs','plyr','dplayer','jwplayer'],'ui.theme':['cerulean','cosmo','cyborg','darkly','flatly','journal','litera','lumen','lux','materia','minty','morph','pulse','quartz','sandstone','simplex','sketchy','slate','solar','spacelab','superhero','united','vapor','yeti','zephyr']};
function sc(i,l,v,c){return '<div class="col-md-3"><div class="card sc border-start border-4 border-'+c+'"><div class="card-body py-3"><div class="d-flex align-items-center"><div class="flex-grow-1"><div class="text-muted small">'+l+'</div><div class="h4 mb-0">'+v+'</div></div><i class="bi '+i+' fs-2 text-'+c+'"></i></div></div></div></div>'}
document.querySelectorAll('[data-tab]').forEach(a=>{a.addEventListener('click',e=>{e.preventDefault();document.querySelectorAll('.sb .nav-link').forEach(n=>n.classList.remove('active'));a.classList.add('active');loadTab(a.dataset.tab)})});
function loadTab(t){$('main').innerHTML='<div class="text-center py-5"><div class="spinner-border"></div></div>';({dashboard:loadDash,credentials:loadCreds,drives:loadDrives,config:loadCfg,sa:loadSA,'google-login':loadGL,security:loadSec})[t]()}

async function loadDash(){try{const[d,c,s,cr]=await Promise.all([api('drives'),api('config'),api('service-accounts'),api('oauth-credentials')]);AD=d.drives;AC=c.config;ASA=s.accounts;ACREDS=cr.credentials;const gv=k=>(AC.find(x=>x.key===k)||{}).value||'';$('main').innerHTML='<h4 class="mb-4"><i class="bi bi-speedometer2"></i> Dashboard</h4><div class="row g-3 mb-4">'+sc('bi-hdd-stack','Drives',AD.length,'primary')+sc('bi-person-badge','Credentials',ACREDS.length,'success')+sc('bi-key','Service Accts',ASA.length,'warning')+sc('bi-sliders','Config',AC.length,'info')+'</div><div class="card"><div class="card-header"><h6 class="mb-0">Overview</h6></div><div class="card-body"><strong>Site:</strong> '+esc(gv('site.name')||'Google Drive Index')+' | <strong>DL:</strong> '+esc(gv('site.download_mode')||'path')+'<hr>'+(AD.length?AD.map(x=>'<div class="d-flex justify-content-between border-bottom py-1"><span><i class="bi bi-hdd me-1"></i>'+esc(x.name)+'</span><span><code class="small me-1">'+esc(x.drive_id)+'</code>'+(x.credential_name?'<span class="badge bg-success">'+esc(x.credential_name)+'</span>':x.sa_name?'<span class="badge bg-warning">'+esc(x.sa_name)+'</span>':'')+'</span></div>').join(''):'<p class="text-muted">No drives.</p>')+'</div></div>'}catch(e){$('main').innerHTML='<div class="alert alert-danger">'+esc(e.message)+'</div>'}}

async function loadCreds(){try{const d=await api('oauth-credentials');ACREDS=d.credentials;var h='<h4 class="mb-4"><i class="bi bi-person-badge"></i> OAuth Credentials</h4><div class="d-flex gap-2 mb-3"><button class="btn btn-outline-danger" onclick="bulkDelCreds()" id="del-sel-cr" style="display:none"><i class="bi bi-trash me-1"></i>Delete Selected</button><button class="btn btn-primary" onclick="showCredM()"><i class="bi bi-plus-lg me-1"></i>Add Credential</button></div><div class="card"><div class="card-body p-0">';if(ACREDS.length){h+='<table class="table table-hover mb-0"><thead><tr><th><input type="checkbox" onchange="togAllCr(this.checked)"></th><th>ID</th><th>Name</th><th>Created</th><th></th></tr></thead><tbody>';ACREDS.forEach(c=>{h+='<tr><td><input type="checkbox" class="cr-cb" value="'+c.id+'" onchange="updCrSel()"></td><td>'+c.id+'</td><td><strong>'+esc(c.name)+'</strong></td><td><small>'+esc(c.created_at||'')+'</small></td><td><button class="btn btn-sm btn-outline-danger" data-x="'+c.id+'" onclick="delOAuthCred(this.dataset.x)"><i class="bi bi-trash"></i></button></td></tr>'});h+='</tbody></table>'}else{h+='<div class="text-center text-muted py-4">No credentials saved. Add OAuth credentials (client_id, secret, refresh_token).<br><small>Values are never displayed after saving.</small></div>'}h+='</div></div>';$('main').innerHTML=h}catch(e){$('main').innerHTML='<div class="alert alert-danger">'+esc(e.message)+'</div>'}}
function showCredM(){$('cred-name').value='';$('cred-cid').value='';$('cred-cs').value='';$('cred-rt').value='';new bootstrap.Modal($('credM')).show()}
async function addOAuthCred(){const n=$('cred-name').value.trim(),ci=$('cred-cid').value.trim(),cs=$('cred-cs').value.trim(),rt=$('cred-rt').value.trim();if(!n||!ci||!cs||!rt)return toast('All fields required','warning');try{await api('oauth-credentials/add',{name:n,client_id:ci,client_secret:cs,refresh_token:rt});bootstrap.Modal.getInstance($('credM')).hide();toast('Saved!');loadCreds()}catch(e){toast(e.message,'danger')}}
async function delOAuthCred(id){if(!confirm('Delete credential?'))return;try{await api('oauth-credentials/delete',{id:+id});toast('Deleted');loadCreds()}catch(e){toast(e.message,'danger')}}

async function loadDrives(){try{const[d,cr,sa]=await Promise.all([api('drives'),api('oauth-credentials'),api('service-accounts')]);AD=d.drives;ACREDS=cr.credentials;ASA=sa.accounts;var h='<div class="d-flex justify-content-between mb-4"><h4 class="mb-0"><i class="bi bi-hdd-stack"></i> Drives</h4></div><div class="d-flex gap-2 mb-3"><button class="btn btn-success" onclick="showBulkM()"><i class="bi bi-plus-circle me-1"></i>Add All Drives</button><button class="btn btn-primary" onclick="showDM()"><i class="bi bi-plus-lg me-1"></i>Add Drive</button><button class="btn btn-outline-danger" onclick="bulkDelDrives()" id="del-sel-dr" style="display:none"><i class="bi bi-trash me-1"></i>Delete Selected</button></div><div class="card"><div class="card-body p-0"><table class="table table-hover mb-0"><thead><tr><th><input type="checkbox" onchange="togAllDr(this.checked)"></th><th>#</th><th>Name</th><th>ID</th><th>Auth</th><th>Status</th><th></th></tr></thead><tbody>';if(AD.length){AD.forEach((x,i)=>{var al=x.credential_name?'<span class="badge bg-success">'+esc(x.credential_name)+'</span>':x.sa_name?'<span class="badge bg-warning">SA:'+esc(x.sa_name)+'</span>':'<span class="badge bg-secondary">default</span>';h+='<tr><td><input type="checkbox" class="dr-cb" value="'+x.id+'" onchange="updDrSel()"></td><td>'+i+'</td><td><strong>'+esc(x.name)+'</strong></td><td><code class="small">'+esc(x.drive_id)+'</code></td><td>'+al+'</td><td>'+(x.enabled?'<span class="badge bg-success">On</span>':'<span class="badge bg-danger">Off</span>')+'</td><td><button class="btn btn-sm btn-outline-primary me-1" data-x="'+x.id+'" onclick="editDr(+this.dataset.x)"><i class="bi bi-pencil"></i></button><button class="btn btn-sm btn-outline-danger" data-x="'+x.id+'" onclick="delDr(+this.dataset.x)"><i class="bi bi-trash"></i></button></td></tr>'})}else{h+='<tr><td colspan="7" class="text-center text-muted py-4">No drives.</td></tr>'}h+='</tbody></table></div></div>';$('main').innerHTML=h}catch(e){$('main').innerHTML='<div class="alert alert-danger">'+esc(e.message)+'</div>'}}
function populateSel(){var c=$('d-cred');c.innerHTML='<option value="">--Select--</option>';ACREDS.forEach(x=>{c.innerHTML+='<option value="'+x.id+'">'+esc(x.name)+'</option>'});var s=$('d-sa');s.innerHTML='<option value="">--Select--</option>';ASA.forEach(x=>{s.innerHTML+='<option value="'+x.id+'">'+esc(x.name)+'</option>'})}
function onAuthTypeChange(){var v=$('d-auth').value;$('d-auth-oauth').style.display=v==='oauth'?'':'none';$('d-auth-sa').style.display=v==='service_account'?'':'none'}
function showDM(){$('dmt').textContent='Add Drive';$('dei').value='';$('dn').value='';$('di').value='';$('dp').checked=false;$('d-auth').value='oauth';populateSel();onAuthTypeChange();$('fetchResult').textContent='';new bootstrap.Modal($('dm')).show()}
function editDr(id){var d=AD.find(x=>x.id===id);if(!d)return;$('dmt').textContent='Edit';$('dei').value=d.id;$('dn').value=d.name;$('di').value=d.drive_id;$('dp').checked=!!d.protect_file_link;populateSel();$('d-auth').value=d.auth_type||'oauth';if(d.credential_id){(d.auth_type==='service_account'?$('d-sa'):$('d-cred')).value=d.credential_id}onAuthTypeChange();$('fetchResult').textContent='';new bootstrap.Modal($('dm')).show()}
async function saveDrive(){var eid=$('dei').value,at=$('d-auth').value,cid=at==='oauth'?$('d-cred').value:$('d-sa').value;var b={name:$('dn').value,drive_id:$('di').value,protect_file_link:$('dp').checked,auth_type:at,credential_id:cid?+cid:null};try{if(eid)await api('drives/update',{...b,id:+eid,enabled:true});else await api('drives/add',b);bootstrap.Modal.getInstance($('dm')).hide();toast(eid?'Updated':'Added');loadDrives()}catch(e){toast(e.message,'danger')}}
async function delDr(id){if(!confirm('Delete?'))return;try{await api('drives/delete',{id});toast('Deleted');loadDrives()}catch(e){toast(e.message,'danger')}}
async function fetchRoot(){var did=$('di').value.trim();if(!did)return toast('Enter Drive ID','warning');var at=$('d-auth').value;var cid=at==='oauth'?$('d-cred').value:$('d-sa').value;if(!cid)return toast('Select a '+at+' first','warning');$('fetchResult').innerHTML='<span class="spinner-border spinner-border-sm"></span> Fetching...';try{var d=await api('drives/fetch-root',{drive_id:did,credential_id:+cid,auth_type:$('d-auth').value});$('fetchResult').innerHTML='<span class="text-success"><i class="bi bi-check-circle"></i> '+esc(d.name)+' ('+esc(d.root_id)+')</span>';if(d.name)$('dn').value=d.name;if(d.root_id)$('di').value=d.root_id}catch(e){$('fetchResult').innerHTML='<span class="text-danger">'+esc(e.message)+'</span>'}}
async function browseShared(){var at=$('d-auth').value;var cid=at==='oauth'?$('d-cred').value:$('d-sa').value;if(!cid)return toast('Select a '+at+' first','warning');$('fetchResult').innerHTML='<span class="spinner-border spinner-border-sm"></span> Loading drives...';try{var d=await api('drives/list-shared',{credential_id:+cid,auth_type:$('d-auth').value});var h='<div class="list-group mt-2">';d.drives.forEach(x=>{h+='<a href="#" class="list-group-item list-group-item-action py-1 px-2" onclick="pickDrive(this)" data-id="'+esc(x.id)+'" data-name="'+esc(x.name)+'"><small>'+(x.type==='shared'?'<i class="bi bi-people me-1"></i>':'<i class="bi bi-person me-1"></i>')+esc(x.name)+'</small> <code class="small float-end">'+esc(x.id)+'</code></a>'});h+='</div>';$('fetchResult').innerHTML=h}catch(e){$('fetchResult').innerHTML='<span class="text-danger">'+esc(e.message)+'</span>'}}
function pickDrive(el){$('di').value=el.dataset.id;$('dn').value=el.dataset.name;$('fetchResult').innerHTML='<span class="text-success"><i class="bi bi-check-circle"></i> Selected: '+esc(el.dataset.name)+'</span>'}

async function loadCfg(){try{var d=await api('config');AC=d.config;var g={};AC.forEach(c=>{var k=c.key.split('.')[0];if(!g[k])g[k]=[];g[k].push(c)});$('main').innerHTML='<div class="d-flex justify-content-between mb-4"><h4 class="mb-0"><i class="bi bi-sliders"></i> Config</h4><div><button class="btn btn-outline-primary btn-sm me-2" onclick="showCM()"><i class="bi bi-plus-lg"></i> Add</button><button class="btn btn-primary btn-sm" onclick="saveCfg()"><i class="bi bi-save"></i> Save</button></div></div>'+Object.keys(g).sort().map(k=>'<div class="card mb-3"><div class="card-header d-flex justify-content-between"><h6 class="mb-0 text-capitalize">'+k+'</h6><span class="badge bg-secondary">'+g[k].length+'</span></div><div class="card-body p-0"><table class="table table-sm mb-0"><tbody>'+g[k].map(c=>{var bl=BK.includes(c.key),so=SK[c.key],inp;if(bl)inp='<select class="form-select form-select-sm ci" data-key="'+esc(c.key)+'"><option value="true"'+(c.value==='true'?' selected':'')+'>true</option><option value="false"'+(c.value!=='true'?' selected':'')+'>false</option></select>';else if(so)inp='<select class="form-select form-select-sm ci" data-key="'+esc(c.key)+'">'+so.map(o=>'<option'+(c.value===o?' selected':'')+'>'+o+'</option>').join('')+'</select>';else inp='<input class="form-control form-control-sm ci" data-key="'+esc(c.key)+'" value="'+esc(c.value)+'">';return '<tr><td style="width:35%"><code class="small">'+esc(c.key)+'</code></td><td>'+inp+'</td><td style="width:40px"><button class="btn btn-sm btn-outline-danger" data-delkey="'+esc(c.key)+'" onclick="delCfg(this.dataset.delkey)"><i class="bi bi-trash"></i></button></td></tr>'}).join('')+'</tbody></table></div></div>').join('')}catch(e){$('main').innerHTML='<div class="alert alert-danger">'+esc(e.message)+'</div>'}}
function showCM(){$('ck').value='';$('cv').value='';new bootstrap.Modal($('cm')).show()}
async function addCfgKey(){var k=$('ck').value.trim(),v=$('cv').value;if(!k)return toast('Key required','warning');try{await api('config/set',{key:k,value:v});bootstrap.Modal.getInstance($('cm')).hide();toast('Added');loadCfg()}catch(e){toast(e.message,'danger')}}
async function delCfg(k){if(!confirm('Delete?'))return;try{await api('config/delete',{key:k});toast('Deleted');loadCfg()}catch(e){toast(e.message,'danger')}}
async function saveCfg(){var items=[];document.querySelectorAll('.ci').forEach(el=>items.push({key:el.dataset.key,value:el.value}));try{await api('config/bulk',{items});toast('Saved!')}catch(e){toast(e.message,'danger')}}

async function loadSA(){try{var d=await api('service-accounts');ASA=d.accounts;$('main').innerHTML='<h4 class="mb-4"><i class="bi bi-key"></i> Service Accounts</h4><div class="d-flex gap-2 mb-3"><button class="btn btn-outline-danger" onclick="bulkDelSAs()" id="del-sel-sa" style="display:none"><i class="bi bi-trash me-1"></i>Delete Selected</button><button class="btn btn-primary" onclick="showSM()"><i class="bi bi-plus-lg me-1"></i>Add Service Account</button></div><div class="card"><div class="card-body p-0"><table class="table table-hover mb-0"><thead><tr><th><input type="checkbox" onchange="togAllSA(this.checked)"></th><th>#</th><th>Name</th><th>Status</th><th></th></tr></thead><tbody>'+(ASA.length?ASA.map((s,i)=>'<tr><td><input type="checkbox" class="sa-cb" value="'+s.id+'" onchange="updSASel()"></td><td>'+(i+1)+'</td><td>'+esc(s.name)+'</td><td>'+(s.enabled?'<span class="badge bg-success">On</span>':'<span class="badge bg-danger">Off</span>')+'</td><td><button class="btn btn-sm btn-outline-danger" data-x="'+s.id+'" onclick="delSA(+this.dataset.x)"><i class="bi bi-trash"></i></button></td></tr>').join(''):'<tr><td colspan="5" class="text-center text-muted py-4">None.</td></tr>')+'</tbody></table></div></div>'}catch(e){$('main').innerHTML='<div class="alert alert-danger">'+esc(e.message)+'</div>'}}
function showSM(){$('sj').value='';new bootstrap.Modal($('sm')).show()}
async function addSA(){var j=$('sj').value.trim();if(!j)return toast('JSON required','warning');try{JSON.parse(j)}catch{return toast('Invalid JSON','danger')}try{await api('service-accounts/add',{json_data:j});bootstrap.Modal.getInstance($('sm')).hide();toast('Added');loadSA()}catch(e){toast(e.message,'danger')}}
async function delSA(id){if(!confirm('Delete?'))return;try{await api('service-accounts/delete',{id});toast('Deleted');loadSA()}catch(e){toast(e.message,'danger')}}

async function loadGL(){try{var d=await api('google-login');var h='<h4 class="mb-4"><i class="bi bi-google"></i> Google Login</h4><div class="card mb-3"><div class="card-header"><h6 class="mb-0">Redirect URI</h6></div><div class="card-body"><div class="alert alert-info mb-0">Add this URI in Cloud Console:<br><br><div class="input-group"><input type="text" class="form-control font-monospace" value="'+REDIRECT_URI+'" readonly id="ruri"><button class="btn btn-outline-secondary" onclick="navigator.clipboard.writeText($(&quot;ruri&quot;).value);toast(&quot;Copied!&quot;)"><i class="bi bi-clipboard"></i></button></div></div></div></div>';h+='<div class="card"><div class="card-header"><h6 class="mb-0">Settings</h6></div><div class="card-body"><div class="mb-3"><label>Enable</label><select class="form-select" id="gl-en"><option value="true"'+(d['auth.enable_social_login']?' selected':'')+'>On</option><option value="false"'+(!d['auth.enable_social_login']?' selected':'')+'>Off</option></select></div><div class="mb-3"><label>Client ID '+(d['google_login.client_id']?'<span class="badge bg-success">Set</span>':'<span class="badge bg-danger">-</span>')+'</label><input class="form-control" id="gl-cid"></div><div class="mb-3"><label>Client Secret '+(d['google_login.client_secret']?'<span class="badge bg-success">Set</span>':'<span class="badge bg-danger">-</span>')+'</label><input type="password" class="form-control" id="gl-cs"></div><button class="btn btn-primary" onclick="saveGL()"><i class="bi bi-save"></i> Save</button></div></div>';$('main').innerHTML=h}catch(e){$('main').innerHTML='<div class="alert alert-danger">'+esc(e.message)+'</div>'}}
async function saveGL(){var b={enabled:$('gl-en').value==='true'};var c=$('gl-cid').value.trim();if(c)b.client_id=c;var s=$('gl-cs').value.trim();if(s)b.client_secret=s;try{await api('google-login/save',b);toast('Saved!');loadGL()}catch(e){toast(e.message,'danger')}}

async function loadSec(){try{var d=await api('security');var h='<h4 class="mb-4"><i class="bi bi-shield-check"></i> Security</h4><div class="card mb-3"><div class="card-header"><h6 class="mb-0">Admin</h6></div><div class="card-body"><div class="row g-3"><div class="col-md-6"><label>Username</label><input class="form-control" id="su" value="'+esc(d['admin.username'])+'"></div><div class="col-md-6"><label>Password '+(d['admin.password_set']?'<span class="badge bg-success">Set</span>':'<span class="badge bg-danger">-</span>')+'</label><input type="password" class="form-control" id="sp" placeholder="New"></div></div><button class="btn btn-primary mt-3" onclick="saveSec()"><i class="bi bi-save"></i> Save</button></div></div>';h+='<div class="card mb-3"><div class="card-header"><h6 class="mb-0">Blocked</h6></div><div class="card-body"><div class="mb-3"><label>Regions</label><input class="form-control" id="sr" value="'+esc(d['security.blocked_regions'])+'"></div><div class="mb-3"><label>ASNs</label><input class="form-control" id="sa2" value="'+esc(d['security.blocked_asn'])+'"></div><button class="btn btn-primary" onclick="saveBlk()"><i class="bi bi-save"></i> Save</button></div></div>';h+='<div class="card"><div class="card-header"><h6 class="mb-0">Crypto</h6></div><div class="card-body"><p>Encrypt: '+(d['security.crypto_key_set']?'<span class="badge bg-success">Set</span>':'<span class="badge bg-danger">-</span>')+' <button class="btn btn-outline-warning btn-sm" onclick="regenKey(&apos;crypto&apos;)">Regen</button></p><p>HMAC: '+(d['security.hmac_key_set']?'<span class="badge bg-success">Set</span>':'<span class="badge bg-danger">-</span>')+' <button class="btn btn-outline-warning btn-sm" onclick="regenKey(&apos;hmac&apos;)">Regen</button></p></div></div>';$('main').innerHTML=h}catch(e){$('main').innerHTML='<div class="alert alert-danger">'+esc(e.message)+'</div>'}}
async function saveSec(){var b={};var u=$('su').value.trim();if(u)b.admin_username=u;var p=$('sp').value;if(p)b.admin_password=p;if(!Object.keys(b).length)return toast('Nothing','warning');try{await api('security/save',b);toast('Saved!');loadSec()}catch(e){toast(e.message,'danger')}}
async function saveBlk(){try{await api('security/save',{blocked_regions:$('sr').value,blocked_asn:$('sa2').value});toast('Saved!')}catch(e){toast(e.message,'danger')}}
async function regenKey(t){if(!confirm('Regenerate '+t+'?'))return;try{await api('security/regenerate-key',{type:t});toast('Done!');loadSec()}catch(e){toast(e.message,'danger')}}

function togAllDr(c){document.querySelectorAll('.dr-cb').forEach(x=>x.checked=c);updDrSel()}
function updDrSel(){var n=document.querySelectorAll('.dr-cb:checked').length;var b=$('del-sel-dr');b.style.display=n?'':'none';b.textContent='Delete Selected ('+n+')'}
async function bulkDelDrives(){var ids=[];document.querySelectorAll('.dr-cb:checked').forEach(x=>ids.push(+x.value));if(!ids.length)return;if(!confirm('Delete '+ids.length+' drive(s)?'))return;try{await api('drives/bulk-delete',{ids});toast('Deleted '+ids.length);loadDrives()}catch(e){toast(e.message,'danger')}}
function togAllCr(c){document.querySelectorAll('.cr-cb').forEach(x=>x.checked=c);updCrSel()}
function updCrSel(){var n=document.querySelectorAll('.cr-cb:checked').length;var b=$('del-sel-cr');if(b){b.style.display=n?'':'none';b.textContent='Delete Selected ('+n+')'}}
async function bulkDelCreds(){var ids=[];document.querySelectorAll('.cr-cb:checked').forEach(x=>ids.push(+x.value));if(!ids.length)return;if(!confirm('Delete '+ids.length+' credential(s)?'))return;try{await api('oauth-credentials/bulk-delete',{ids});toast('Deleted '+ids.length);loadCreds()}catch(e){toast(e.message,'danger')}}
function togAllSA(c){document.querySelectorAll('.sa-cb').forEach(x=>x.checked=c);updSASel()}
function updSASel(){var n=document.querySelectorAll('.sa-cb:checked').length;var b=$('del-sel-sa');if(b){b.style.display=n?'':'none';b.textContent='Delete Selected ('+n+')'}}
async function bulkDelSAs(){var ids=[];document.querySelectorAll('.sa-cb:checked').forEach(x=>ids.push(+x.value));if(!ids.length)return;if(!confirm('Delete '+ids.length+' service account(s)?'))return;try{await api('service-accounts/bulk-delete',{ids});toast('Deleted '+ids.length);loadSA()}catch(e){toast(e.message,'danger')}}
function onBulkAuthChange(){var v=$('bulk-auth').value;$('bulk-oauth-sel').style.display=v==='oauth'?'':'none';$('bulk-sa-sel').style.display=v==='service_account'?'':'none'}
function showBulkM(){$('bulk-auth').value='oauth';var c=$('bulk-cred');c.innerHTML='<option value="">--Select--</option>';ACREDS.forEach(x=>{c.innerHTML+='<option value="'+x.id+'">'+esc(x.name)+'</option>'});var s=$('bulk-sa');s.innerHTML='<option value="">--Select--</option>';ASA.forEach(x=>{s.innerHTML+='<option value="'+x.id+'">'+esc(x.name)+'</option>'});onBulkAuthChange();$('bulk-result').innerHTML='';$('bulk-btn').disabled=false;new bootstrap.Modal($('bulkM')).show()}
async function bulkAddDrives(){var at=$('bulk-auth').value;var cid=at==='oauth'?$('bulk-cred').value:$('bulk-sa').value;if(!cid)return toast('Select a credential first','warning');$('bulk-btn').disabled=true;$('bulk-result').innerHTML='<div class="d-flex align-items-center mt-2"><span class="spinner-border spinner-border-sm me-2"></span> Fetching drives and adding...</div>';try{var d=await api('drives/bulk-add',{credential_id:+cid,auth_type:at});$('bulk-result').innerHTML='<div class="alert alert-success mt-2 mb-0"><i class="bi bi-check-circle"></i> '+esc(d.message)+'</div>';toast(d.message);loadDrives()}catch(e){$('bulk-result').innerHTML='<div class="alert alert-danger mt-2 mb-0">'+esc(e.message)+'</div>';toast(e.message,'danger')}finally{$('bulk-btn').disabled=false}}
loadDash();</script></body></html>`;
}
